import os

DATABASE_URL = os.environ.get("DATABASE_URL")
CLIENT_ID = os.environ.get("CLIENT_ID")
CLIENT_SECRET = os.environ.get("CLIENT_SECRET")
CLIENT_TOKEN = os.environ.get("CLIENT_TOKEN")
OWNER_ID = os.environ.get("OWNER_ID")
DESCRIPTION = os.environ.get("DESCRIPTION")

IMGUR_CLIENT_ID = os.environ.get("IMGUR_CLIENT_ID")
IMGUR_CLIENT_SECRET = os.environ.get("IMGUR_CLIENT_SECRET")
IMGUR_ACCESS_TOKEN = os.environ.get("IMGUR_ACCESS_TOKEN")
IMGUR_REFRESH_TOKEN = os.environ.get("IMGUR_REFRESH_TOKEN")

MOD_ROLE_ID = 535886249458794547
GUILD_OWNER_ID = 533370022295502879
