import os

DATABASE_URL = os.environ["DATABASE_URL"]
CLIENT_ID = os.environ["CLIENT_ID"]
CLIENT_SECRET = os.environ["CLIENT_SECRET"]
CLIENT_TOKEN = os.environ["CLIENT_TOKEN"]
OWNER_ID = os.environ["OWNER_ID"]
DESCRIPTION = os.environ["DESCRIPTION"]

IMGUR_CLIENT_ID = os.environ["IMGUR_CLIENT_ID"]
IMGUR_CLIENT_SECRET = os.environ["IMGUR_CLIENT_SECRET"]
IMGUR_ACCESS_TOKEN = os.environ["IMGUR_ACCESS_TOKEN"]
IMGUR_REFRESH_TOKEN = os.environ["IMGUR_REFRESH_TOKEN"]

MOD_ROLE_ID = 535886249458794547
GUILD_OWNER_ID = 533370022295502879
